### ISSUE TITLE
Some Swagger syntax are not supported in Synapse

### ISSUE THREAD

**Issue by prabushi** [wso2/integration-studio#100]
**Description:**
Some swagger syntax are not supported in Synapse(For example properties, schema, consumers, etc.)

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by sajithaliyanage** [comment]
Fixed in the latest release. https://github.com/wso2/integration-studio/issues/618
