### ISSUE TITLE
Improvement in work of TemplateMediator - space between parameter name and its value

### ISSUE THREAD

**Issue by Thilinika** [wso2/integration-studio#1001]
**Description:**
 In the TemplateMediator, you need to indent between the parameter name and its value, since they are displayed together (without any space between them)

![Pasted image](https://user-images.githubusercontent.com/33649582/150932642-2f045872-70fb-42e8-8d86-bd30fbf4e213.png)

Can this issue be addressed?

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
Integration Studio 8.0.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Tharsanan1** [comment]
It's only reproducible in windows OS.
