### ISSUE TITLE
Creating new REST API wizard has a irrelevant blue box

### ISSUE THREAD

**Issue by arunans23** [wso2/integration-studio#1051]
**Description:**

<img width="582" alt="Screenshot 2022-03-10 at 15 42 51" src="https://user-images.githubusercontent.com/17047910/157640492-f026f47b-4785-4a74-8cb2-9374e978580c.png">

While creating new REST API via the wizard, it has a irrelevant blue box surrounding the Artifact word in the first option.

**Comment by rosensilva** [comment]
fixed with https://github.com/wso2/integration-studio/pull/1066
