### ISSUE TITLE
Remove HTTP Client tool related information and screenshots from the docs and the Integration Studio samples

### ISSUE THREAD

**Issue by arunans23** [wso2/integration-studio#1054]
**Description:**

https://apim.docs.wso2.com/en/latest/integrate/develop/wso2-integration-studio/#http-client

We need to remove occurrences like above from the Documentation.

**Comment by Tharsanan1** [comment]
Already merged the changes to the master branch through this PR: https://github.com/wso2/docs-apim/pull/5192/files.

**Comment by arunans23** [comment]
We need to update Studio samples as well. 

<img width="308" alt="Screenshot 2022-03-14 at 15 21 12" src="https://user-images.githubusercontent.com/17047910/158148415-ad7ee15c-28ff-4968-821e-82ab1dab4112.png">
