### ISSUE TITLE
Cannot create a REST API Artifact

### ISSUE THREAD

**Issue by dinethpiyumantha** [wso2/integration-studio#1116]
![err](https://user-images.githubusercontent.com/55337770/168050666-cdee5cfc-7ca9-4066-9bda-d071a450815a.JPG)

**Comment by aravindkesavarapu** [comment]
I am also facing the same issue with integration studio 8.1v.

Any one help me resolve this issue

**Comment by aryawiratama18** [comment]
Me too. I'm using Macbook Air M1 2020
