### ISSUE TITLE
Starting Micro Integrator Server 4.1.0 has encountered a problem

### ISSUE THREAD

**Issue by Andrea-Cavallo** [wso2/integration-studio#1139]
Every time I try to run my application I have this error: 
Working directory does not exist: runtime/microesb

But i do have this directory. How can I fix this issue?
thanks , I tried to delete and download Integration Studio multiple times..

**Comment by jdeguzman-teligent** [comment]
I have similar problem and what I did is the following (it worked in my setup): 

- Go to Run Configurations panel
- Select the Micro Integrator Server (this is the Generic Server instance)
- on the right pane, adjust the VM arguments to point to correct folder (under Arguments tab)
- next (under Classpath tab) remove all 'User Entries' entries that has incorrect folder path
- (still under Classpath tab), after removing all the incorrect folder path, add all jar files by clicking 'Add External JARs' and locate all jar files under the correct folder path -- normally it is under <Correct Path>\IntegrationStudio\runtime\microesb\wso2\lib\ folder
- in adding bin and lib, use the 'Advanced...' and select the 'Add Variable String:' and enter the 'bin - <correct path here>'

And try running again, it should work :)
