### ISSUE TITLE
WSO2 Integration Studio doesn't support NTLM mediator

### ISSUE THREAD

**Issue by mcarroa** [wso2/integration-studio#1180]
IS 8.0.1 doesn't support NTLM mediator configuration.-
![image](https://user-images.githubusercontent.com/48556323/207854292-6ef3cafc-d736-4234-96ce-1dbc3d862d74.png)

**Comment by rosensilva** [comment]
NTLM mediator support was introduced with IS 8.1.0. Please download latest studio and try.
