### ISSUE TITLE
PortOffset value does not work in EI 6.6.0 server

### ISSUE THREAD

**Issue by prabushi** [wso2/integration-studio#149]
**Description:**
PortOffset value does not correctly work when added an EI 6.6.0 server.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by rosensilva** [comment]
Fixed in Integration Studio 8.0.0
