### ISSUE TITLE
Project build error on Mac

### ISSUE THREAD

**Issue by prabushi** [wso2/integration-studio#152]
**Description:**
Create an Integration project and right-click on the MMM project and 'Maven build'. It results with the following error on Mac.
<img width="1680" alt="shazni" src="https://user-images.githubusercontent.com/5234623/87017202-507cfd80-c1ed-11ea-970b-ce0bbf72ef8a.png">

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by gspadotto** [comment]
I don't know if this is the case, but I was able to fix the issue by assuring that the maven executable is indeed in the 
$PATH. 

I check this fact by launching the build with the "-e" switch.

To have the maven executable in the "system" PATH on a Mac, create the mvn file inside "/etc/paths.d" and set its content
to the path of the mvn executable, like this: 
/usr/local/apache-maven-3.6.0/bin/
