### ISSUE TITLE
Make Connection window configuration area scrollable

### ISSUE THREAD

**Issue by dinuish94** [wso2/integration-studio#168]
**Description:**
Make Connection window configuration area scrollable and increase space for labels.

Please refer below image.
<img width="689" alt="Screenshot 2020-06-27 at 12 58 13" src="https://user-images.githubusercontent.com/16366956/85917258-2d119480-b876-11ea-8582-fed7d0c5173d.png">

**Comment by rosensilva** [comment]
Fixed in the Integration Studio 8.0.0
