### ISSUE TITLE
Add dataservices call mediator tooling support to the integration studio

### ISSUE THREAD

**Issue by chanikag** [wso2/integration-studio#171]
**Description:**
The dataservices call mediator is added to MI by [1]. The tooling support should be included.

[1] https://github.com/wso2/micro-integrator/pull/1714

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by rosensilva** [comment]
added DSS mediator support in IS 8.0.0
