### ISSUE TITLE
[ DSS Editor ] Data Source configs are not properly rendered in UI

### ISSUE THREAD

**Issue by Nirothipan** [wso2/integration-studio#176]
**Description:**
As in the following image, the field values  ( data source type , engine etc ) are not rendered in UI properly. 

![Screenshot from 2020-06-20 09-28-34](https://user-images.githubusercontent.com/24619763/85190696-75f6a580-b2d8-11ea-950c-8dc30796fdb6.png)

version : 7.1.0-alpha

**Comment by rosensilva** [comment]
fixed in IS 8.0.0
