### ISSUE TITLE
Expression buttons on the connection wizard are not working

### ISSUE THREAD

**Issue by prabushi** [wso2/integration-studio#191]
**Description:**
Expression buttons on the connection wizard of the new connector properties view are not working.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by sajithaliyanage** [comment]
Already fixed in the 8.0.0-beta release from https://github.com/wso2/integration-studio/issues/676
