### ISSUE TITLE
Fails when a REST API is created from a swagger that contains spaces in the title

### ISSUE THREAD

**Issue by HeshanSudarshana** [wso2/integration-studio#225]
**Description:**

An application fails to run when it includes a REST API created using a swagger file with a title that contains spaces in it.

**Steps to reproduce:**

1. Create an integration project.
2. Create a new REST API using the project.
3. Provide a swagger file with spaces in the title (eg: "Swagger Petstore")
4. Try to run the application in micro integrator.

**Comment by rosensilva** [comment]
Fixed in latest Integration Studio 8.0.0
