### ISSUE TITLE
[Connector] Cleanup connector parameter view

### ISSUE THREAD

**Issue by milindaperera** [wso2/integration-studio#241]
**Description:**
Clean the connector parameter view by removing "Call Template Parameter" entries displayed when displaying for connectors.

<img width="1680" alt="Screenshot 2020-04-21 at 00 28 59" src="https://user-images.githubusercontent.com/7402364/79789480-e5e3c080-8367-11ea-9a10-649621981b1c.png">

**Comment by rosensilva** [comment]
Fixed with new connector properties view
