### ISSUE TITLE
When adding connectors to the workspace, sometimes it does not display the connector store. 

### ISSUE THREAD

**Issue by isuruuy429** [wso2/integration-studio#243]
**Description:**
1. Create an ESB Solution project. 
2. Right-click on the ESB project and click on Add or Remove Connector. 
3. Click on Add Connector. 

Sometimes it does not display the connector store. Getting the following message. This issue is intermittent. 

<img width="525" alt="Screen Shot 2020-04-15 at 6 15 38 PM" src="https://user-images.githubusercontent.com/31693103/79338570-277a0300-7f45-11ea-9600-960df64a52a7.png">

Tested on Integration Studio 7.0.0
MacOS

**Comment by yasirjanjua** [comment]
it is also reproducable on 7.2.0
