### ISSUE TITLE
Add new attribute "publishSwagger" to the dataservice.

### ISSUE THREAD

**Issue by GDLMadushanka** [wso2/integration-studio#254]
**Description:**
We introduced a new feature to expose a Swagger definition from the data service. 
When the users need to change the automatically generate swagger,  they can add the custom swagger definition to the registry and expose it via the publishSwagger option. 

Ex :
```
<data name="DS2" publishSwagger="gov:/custom/sample.json" transports="http https local">
   <config enableOData="false" id="DSource2">
      <property name="driverClassName">com.mysql.jdbc.Driver</property>
```
To support this new attribute we need to add option to configure publishSwagger by giving registry resource selector. 

**Suggested Labels:**
Improvement

**Related Issues:**
wso2/micro-integrator/issues/1331

**Comment by rosensilva** [comment]
@GDLMadushanka is this still valid?
