### ISSUE TITLE
Cannot import existing projects into Maven Multi Module Project

### ISSUE THREAD

**Issue by abeykoon** [wso2/integration-studio#26]
**Description:**

Steps to reproduce. 

1. Create an integration project using studio and export it to an external location as a folder. 
2. Switch workplace and open studio in a new workplace 
3. Create a Maven Multi Module project there. 
4. Right click the MMM project and import the exported project above. 

It is not added into the MMM project. It always imported to the root workplace. 

<img width="614" alt="Screenshot 2020-12-18 at 13 38 54" src="https://user-images.githubusercontent.com/4967046/102590428-92b05080-4136-11eb-9223-109d9c4c30fa.png">

**Comment by sdkottegoda** [comment]
I followed the following steps:

1. Create new MMM project by selecting the projects in the workspace to the MMM.
2. The project is loaded with the following error.

![image](https://user-images.githubusercontent.com/1330107/102713396-0052ad00-42ee-11eb-8e88-c25602ed8cf9.png)
