### ISSUE TITLE
[OpenAPI] OpenAPI 3.0 support for API generation

### ISSUE THREAD

**Issue by milindaperera** [wso2/integration-studio#271]
**Description:**
Add support for OpenAPI 3.0 support for API template generation feature in IntegrationStudio

**Related Issues:**
https://github.com/wso2/product-ei/issues/5018

**Comment by GDLMadushanka** [comment]
Fixed in https://github.com/wso2/integration-studio/pull/640

**Comment by GDLMadushanka** [comment]
Duplicate of https://github.com/wso2/integration-studio/issues/618
