### ISSUE TITLE
Cannot create new integration project in arbitrary directory

### ISSUE THREAD

**Issue by daoxxx** [wso2/integration-studio#28]
**Description:**
New Integration project (Maven multimodule) is always created in the root workspace.  Location option doesn't affect this behaviour.

**Affected Product Version:**
7.1.0
**OS, DB, other environment details and versions:**    
Ubuntu 20.04

**Steps to reproduce:**
Create new directory ~/projects
In the Integration Studio open New Integration project.. menu.
Uncheck Use default location.
In the Location field browse to the ~/projects dir.
<img src="https://user-images.githubusercontent.com/18573254/102600312-ba4fea80-412f-11eb-8b81-8b228c85f182.png" width="60%" height="30%">
Finish.
New project will be created in the root workspace dir

```
dao@ubook:~/projects$ tree ~/projects
/home/dao/projects

0 directories, 0 files
dao@ubook:~/projects$ tree -d ~/IntegrationStudio/workspace_test/
/home/dao/IntegrationStudio/workspace_test/
└── new
    ├── newCompositeExporter
    │   └── newCompositeExporter
    └── newConfigs
        └── newConfigs
            ├── src
            │   └── main
            │       └── synapse-config
            │           ├── api
            │           ├── endpoints
            │           ├── inbound-endpoints
            │           ├── local-entries
            │           ├── message-processors
            │           ├── message-stores
            │           ├── proxy-services
            │           ├── sequences
            │           ├── tasks
            │           └── templates
            └── test
                └── resources
                    └── mock-services
```

**Comment by sajithaliyanage** [comment]
Duplicate: https://github.com/wso2/integration-studio/issues/52
