### ISSUE TITLE
CSV datasource is not selected in the UI correctly while deserializing from source

### ISSUE THREAD

**Issue by Drifftr** [wso2/integration-studio#281]
**Description:**
CSV datasource is not selected in the UI from the source editor.

**Steps to reproduce:**
1. Start a Data service project.
2. Copy the following sample to source editor[1].
3. Switch back to Design tab.
4. Datasource will be still selected as RDBMS/Default

[1]. https://ei.docs.wso2.com/en/latest/micro-integrator/use-cases/examples/data_integration/csv-data-service/

**Comment by tharakamd** [comment]
The issue is not reproducing in Integration Studio 8.0.0 - RC1
