### ISSUE TITLE
Maven Multimodule project creates extra directory level

### ISSUE THREAD

**Issue by daoxxx** [wso2/integration-studio#29]
**Description:**
New Integration Project wizard creates Maven Multi module project with extra directory level for every subproject.
Is it a bug or a feature?

**Affected Product Version:**
7.1.0
**OS, DB, other environment details and versions:**    
Ubuntu 20.04

**Steps to reproduce:**
Create new Integration Project
<img src="https://user-images.githubusercontent.com/18573254/102602717-f59fe880-4132-11eb-86f1-3fc41bd13e94.png" alt="drawing" width="60%" />
Every subproject is wrapped with extra unnecessary (?) directory with the same name.
```
dao@ubook:~/projects$ tree ~/IntegrationStudio/workspace_test/
/home/dao/IntegrationStudio/workspace_test/
└── new
    ├── newCompositeExporter
    │   └── newCompositeExporter
    │       └── pom.xml
    ├── newConfigs
    │   └── newConfigs
    │       ├── artifact.xml
    │       ├── pom.xml
    │       ├── src

```

**Comment by sajithaliyanage** [comment]
Please try out the [latest integration studio release](https://github.com/wso2/integration-studio/releases) since we have done some fixes around the project structure. Reopen the ticket if any concerns occur on this issue.
