### ISSUE TITLE
auto remove endpoint drop templet

### ISSUE THREAD

**Issue by xie-shujian** [wso2/integration-studio#312]
**Description:**
the studio auto remove
endpoint in send
drop
sequence templete defined in another interface

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by rosensilva** [comment]
Fixed in Integration Studio 7.2.0 onwards
