### ISSUE TITLE
Inbound enpoint parameters get dropped while saving

### ISSUE THREAD

**Issue by daoxxx** [wso2/integration-studio#32]
**Description:**
When editing Inbound enpoint (custom class) with default ESB Editor. Parameters that are pointing to a registry keys get deleted while saving.

**Affected Product Version:**
7.1.0
**OS, DB, other environment details and versions:**    
Linux
**Steps to reproduce:**
Create custom Inbound endpoint
Add parameter whose value is stored in the registry
Example:
`<parameter name="bootstrap.servers" key="gov:config/kafka/kafka_bootstrap_servers"/>`
Save it.
Open endpoint for editing.
Parameter "bootstrap.servers" is absent

**Comment by sajithaliyanage** [comment]
Duplicate: https://github.com/wso2/integration-studio/issues/51
