### ISSUE TITLE
Setting port offset doesn't work for EI 6.6.0 server.

### ISSUE THREAD

**Issue by isudana** [wso2/integration-studio#33]
Port offset is not getting set. When you specify an offset, deployment of artifacts fails with a "connection refused"

Integration Studio 7.2.0 Beta

**Comment by isudana** [comment]
Same for MI 1.1.0

**Comment by rosensilva** [comment]
FIxed for EI server versions 6.0.0 to 6.6.0.
MI implementation is different from the EI servers, hence opened a new issue to track
https://github.com/wso2/integration-studio/issues/710
