### ISSUE TITLE
Add KeyStore parameter tags to the source of HTTPS Inbound endpoint

### ISSUE THREAD

**Issue by prabushi** [wso2/integration-studio#332]
**Description:**
Originally reported in https://github.com/wso2/product-ei/issues/4059

When creating an HTTPS inbound endpoint in Integration studio, parameters for the KeyStore (following code segment) is not in the source. But to create an HTTPS inbound endpoint, KeyStore parameters are required thing. 
```
<parameter xmlns="" name="keystore">
            <KeyStore>
               <Location>repository/resources/security/wso2carbon.jks</Location>
               <Type>JKS</Type>
               <Password>wso2carbon</Password>
               <KeyPassword>wso2carbon</KeyPassword>
            </KeyStore>
</parameter>
```

**Suggested Labels:**
Type/Improvement

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Vathsan** [comment]
We need to update the trust store parameter as well. It seems we do not separate fields to configure trust store location, type and password.
![image](https://user-images.githubusercontent.com/29911181/114167679-e3012780-994c-11eb-9e31-566c09d91d97.png)
Sample config: 
```
<p:parameter name="truststore">
    <TrustStore xmlns="">
        <Location>repository/resources/security/client-truststore.jks</Location>
        <Type>JKS</Type>
        <Password>wso2carbon</Password>
    </TrustStore>
</p:parameter>
```
