### ISSUE TITLE
New Data Service wizard does not allow to use the existing data source. 

### ISSUE THREAD

**Issue by VirajHasitha** [wso2/integration-studio#341]
**Description:**
When creating a new data service using the tooling, it is not allowing to use the data source which has already created in the project and it is mandatory to create the data source within the wizard itself. 

![Screenshot from 2019-10-23 10-24-26](https://user-images.githubusercontent.com/9976728/67359178-37112400-f580-11e9-9d9c-977bf6fc7d7f.png)

**Affected Product Version:**
Integration Studio 7.0.0

**Comment by rosensilva** [comment]
Fixed with new DSS editor from Integration Studio 7.1.0
