### ISSUE TITLE
Improve path to swagger definition in API creation wizard

### ISSUE THREAD

**Issue by prabushi** [wso2/integration-studio#343]
**Description:**
Improve "Path to Swagger Definition" in API creation wizard to get the path from registry.

![swagger_url](https://user-images.githubusercontent.com/5234623/67078235-833e1c00-f1ae-11e9-82b6-e34f43517e58.png)

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by rosensilva** [comment]
Swagger API generation is revamped with Integration Studio 8.0.0
