### ISSUE TITLE
Add registry properties support for Micro Integrator

### ISSUE THREAD

**Issue by prabushi** [wso2/integration-studio#358]
**Description:**
Add registry resource/collection properties support for Micro Integrator via Integration Studio.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by rosensilva** [comment]
Fixed with Integration Studio 8.0.0
