### ISSUE TITLE
xpath 2.0 expression /node/(price * quantity) no allowed

### ISSUE THREAD

**Issue by rosensilva** [wso2/integration-studio#422]
**Description:**
some valid xpath 2.0 expressions are not allowed in dev studio.

Try:  /node/(price * quantity) -> 

Invalid xpath expression for attribute expression: /node/(price * quantity)

**Comment by TomasTokaMrazek** [comment]
Apparently still not fixed.

`//*[local-name()='Type']/text() = ('A', 'B','C')` Simple XPath 2.0 with check for value in array of strings still throws an error.

![image](https://user-images.githubusercontent.com/15164568/221011833-58a18a08-5f77-4844-8221-d5b3240c834d.png)

Jaxen XPath engine should be long ago replaced with Saxon, which would also bring support for XPath 3.0.
