### ISSUE TITLE
Integration Studio not working in Mac OS Big Sur Version 11.0.1 (20B29)

### ISSUE THREAD

**Issue by thimithagamage** [wso2/integration-studio#44]
**Description:**
UI elements do not display correctly, getting a null pointer exception when trying to open an imported project.
<img width="655" alt="Screenshot 2020-11-17 at 12 42 07" src="https://user-images.githubusercontent.com/40795130/99357980-e3801f80-28d2-11eb-8e9b-d33f0db365c7.png">
**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
Integration Studio 7.1.0

**OS, DB, other environment details and versions:**    
Mac OS 11.0.1 (20B29)
**Steps to reproduce:**
Open integration studio and try to open a project in workspace.

**Related Issues:**

**Comment by sajithaliyanage** [comment]
@yasirjanjua We were unable to reproduce this issue locally. Can you try to import a connector in a new workspace and check whether the issue still persists? If yes, please create a new issue by specifying more details.

**Comment by BeParis** [comment]
After upgrading to MacOs Big Sur, then upgrade my Integration Studio 7.0.2 with latest Integration Studio 7.2.0 package I'm not able to open my projects anymore.  The application tells me it is not able to find (open) the ".project" files, but of course these files are present in each project folder.   I've defined Integration Studio 7.2.0 in group"developement tool" in macos "System preferences > Security and Privacy > Privacy" but no success.  What should I do ?
