### ISSUE TITLE
Cannot create an API which forwards requests to a load balance endpoint with defined endpoints

### ISSUE THREAD

**Issue by sdkottegoda** [wso2/integration-studio#533]
**Description:**
Unable to create an API in devstudio (RCP pack) with a call mediator calling a load balance group with a **defined** endpoint list.
Steps to reproduce:
1. Create an API in dev studio.
2. Add a call mediator.
3. Add a loag balance group inside the call mediator.
4. Add 2 **defined** endpoints to the group
5. Save the load balance group
6. Try to save the api configuration, the following error will prevent you from saving the load balance endpoint and navigating to the design view.

```Invalid mediator <loadbalance algorithm="org.apache.synapse.endpoints.algorithms.RoundRobin"/>```

**Comment by rosensilva** [comment]
Fixed in Integration Studio 8.0.0
