### ISSUE TITLE
Cannot add registry resource property using EI tooling

### ISSUE THREAD

**Issue by godwinamila** [wso2/integration-studio#536]
**Description:**
After creating a registry resource project and add a registry resource, it's not allowing to add registry properties 

**Suggested Labels:**
tooling

**Suggested Assignees:**

**Affected Product Version:**
6.2.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by rosensilva** [comment]
Fixed in the latest 8.0.0 release
