### ISSUE TITLE
Unable to save the modifications made in json payload at the swagger editor from the integration studio 7.1.0

### ISSUE THREAD

**Issue by karunarathneeshani** [wso2/integration-studio#621]
**Description**
After creating a Rest API using a swagger file in Integration studio 7.1.0 and modify the created API from the swagger editor, the modifications can not be saved. This means, although the default resource description changed with the modifications, it cannot be saved in the API. The saved feature is not enabled and if move back to the source view and again move to the swagger editor, the modifications change to the previous values.

**Suggested Labels:**
Integration studio 7.1.0

**Steps to reproduce:**
1) Create a sample API using a swagger file(simple_petstore.yaml) by following wso2 documentation[1].
2) After creating the API, move to the swagger editor and change the JSON "payload" to another value. ( _Although the default resource description changed with the modifications, it cannot be saved. The saved feature is not enabled._ )
3) Move back to the source view and again move to the swagger editor. The modifications have changed to the previous values.
[1] https://ei.docs.wso2.com/en/latest/micro-integrator/use-cases/examples/rest_api_examples/publishing-a-swagger-api/

**Comment by sajithaliyanage** [comment]
Fixed in 8.0.0-m7 release. From this release onwards, the Integration Studio only supports OAS 3(swagger 3) version. However, if someone wants to publish their APIs with swagger 2.0 definition, this can be achieved through the **publishSwagger** API configuration.
