### ISSUE TITLE
In ubuntu-20.04, when using integration studio 7.2.0, in the getting started page, buttons for creating new projects are not working

### ISSUE THREAD

**Issue by Thilinika** [wso2/integration-studio#637]
**Description:**
In ubuntu-20.04, when using integration studio 7.2.0, in the getting started page, following buttons for creating new projects are not working.

![Screenshot from 2021-01-11 14-47-08](https://user-images.githubusercontent.com/33649582/104204106-eae72380-5452-11eb-9c3a-23e73b6fdb31.png)

**Related Issues:**

**Comment by sajithaliyanage** [comment]
Could you please use a new workspace location to start Integration Studio 7.2.0 release, and check whether the issue still persists? However, we were unable to reproduce the issue.
