### ISSUE TITLE
Highlight the tab name if there is any mandatory param under the tab menu

### ISSUE THREAD

**Issue by Shakila** [wso2/integration-studio#64]
**Description:**
**File Locking Behavior** is a mandatory parameter under Advanced configuration. We can highlight the tab name **Advanced** with '*'. Otherwise the advanced configuration can be ignored by the user.
<img width="594" alt="FileConnector" src="https://user-images.githubusercontent.com/2033965/100221663-ffbd3580-2f3e-11eb-8d3c-743f0451ad23.png">

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
File conector 4.0.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by tharakamd** [comment]
Adding required parameters in the **Advanced** tab is not recommended. If a parameter is required, then it should not belong to advanced configurations. You can use default values to any parameter if needed. And now the users cannot finish the connection dialog box without filling in all the required fields and they would get an error message stating the missing value. Therefore, no need to implement this in the Integration studio.
