### ISSUE TITLE
Embedded Micro Integrator Configuration is not working 

### ISSUE THREAD

**Issue by rosensilva** [wso2/integration-studio#665]
**Description:**
This is an intermittent issue where the changes in the "Embedded Micro Integrator Configuration" does not apply to the embedded micro integrator.
<img width="1748" alt="Screenshot 2021-03-10 at 08 42 57" src="https://user-images.githubusercontent.com/13344872/110570864-9f17d880-817c-11eb-97eb-c2c8d8b03167.png">

**Comment by sajithaliyanage** [comment]
Relates to: https://github.com/wso2/integration-studio/issues/715
