### ISSUE TITLE
Open dashboard option get stuck in runtime services view

### ISSUE THREAD

**Issue by nandika** [wso2/integration-studio#673]
**Description:**
Integration Studio 8.0 alpha on windows. See the attached image

**Suggested Labels:**

![dashboardstuck](https://user-images.githubusercontent.com/2908631/110630375-46236100-81cb-11eb-827f-9f0829b2ee4d.png)

**Suggested Assignees:**

**Affected Product Version:**
Integration Studio 8.0 alpha

**OS, DB, other environment details and versions:**    
Windows 10

**Steps to reproduce:**

**Related Issues:**

**Comment by sajithaliyanage** [comment]
FIX: The protocol should be **HTTPS** and the port should be **9743**.
