### ISSUE TITLE
Target property not visible in Call mediator

### ISSUE THREAD

**Issue by arunans23** [wso2/integration-studio#680]
**Description:**

When Target type is selected as Property in Call mediator, the property field is not visible enough to type the property.

![Screenshot 2021-03-14 at 23 25 19](https://user-images.githubusercontent.com/17047910/111078702-d7bd0680-851c-11eb-8dcc-6237a7d956fb.png)

**Affected Product Version:**
IS 8.0.0-alpha

**Comment by sajithaliyanage** [comment]
Duplicate issue: https://github.com/wso2/integration-studio/issues/684
