### ISSUE TITLE
Error while starting embedded MI server

### ISSUE THREAD

**Issue by sajithaliyanage** [wso2/integration-studio#704]
**Description:**
$subject. When we run the integration solution with the embedded MI server, it shows an error as follows.

![Screenshot 2021-03-18 at 10 56 24](https://user-images.githubusercontent.com/12485208/111577673-bd16b600-87d8-11eb-8a33-e39a1de51ceb.png)

**Suggested Labels:**
Type/Bug

**OS**: macOS

**Comment by rosensilva** [comment]
Please verify, you have installed tooling as **IntegrationStudio** (without any prefix or suffix) in the Application directory
