### ISSUE TITLE
Creating and uploading message mediation sequence using Integration Studio not working

### ISSUE THREAD

**Issue by indikasampath2000** [wso2/integration-studio#747]
**Description:**
Please refer to https://github.com/wso2/product-apim/issues/10625

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
Integration Studio 8.0.0-Alpha

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by isudana** [comment]
Closing since original issue is closed.
