### ISSUE TITLE
Cannot export project artifact and run when application name is renamed in Mac OS

### ISSUE THREAD

**Issue by karunarathneeshani** [wso2/integration-studio#750]
**Description:**
The project artifacts cannot be exported and run the application name is renamed in Mac os.

**Affected Product Version:**
Integration Studio 7.2.0

**OS:**    
Mac OS Catalina 10.15.7

**Steps to reproduce:**
1. Download the latest Integration studio to Mac and install it. The installation will be in the Mac Applications directory.
2. Rename the application name to something like **IntegrationStudio 7.**
3. Launch the Integration studio and deploy the sample HelloWorld service.
4. Right click on the carbon application project and click on **export artifacts and run**
3. You will be able to observe the below error.
![StudioError](https://user-images.githubusercontent.com/28178905/110806458-18601a00-82a8-11eb-9d3c-314630a27933.png)

**Comment by sajithaliyanage** [comment]
Relates: https://github.com/wso2/integration-studio/issues/707

**Comment by sajithaliyanage** [comment]
Fixed: https://github.com/wso2/integration-studio/pull/751
