### ISSUE TITLE
When there are two artifacts with same name in 2 different projects, the studio does not export the selected artifact when exporting composite application.

### ISSUE THREAD

**Issue by dulanjalidilmi** [wso2/integration-studio#788]
**Description:**
The studio cannot identify the selected api when exporting the capp.
Please find the steps to reproduce the issue.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

1. Create 2 projects
2. Create 2 artifacts (api) with with same name, but with different configs.
3. Export the second created project.
4. But the api deployed will be the first created project.

**Related Issues:**

**Comment by isudana** [comment]
This is a known limitation in the design, let's target to fix this in 8.0.1.
