### ISSUE TITLE
Implement a mechanism to configure Service Catalog information from Integration Studio

### ISSUE THREAD

**Issue by Asitha** [wso2/integration-studio#79]
**Description:**

Need to provide a set of UI elements to configure service catalog related information in from the integration studio for Micro Integrator artifacts.

**Related Issues:**

https://github.com/wso2/devstudio-tooling-ei/issues/1297

**Comment by GDLMadushanka** [comment]
Duplicate of https://github.com/wso2/integration-studio/issues/618
