### ISSUE TITLE
after update i am always getting two temporary files deployment for every project

### ISSUE THREAD

**Issue by ashoka777** [wso2/integration-studio#819]
**Description:**

i updated my integration studio 7.2.0.i deployed one project in that no schedule task, no sequence.i closed all my projects also but when i run new project the task and sequence files are deploying my embedded micro integrator.that two files are temp files i deleted that files also again it comes back.  
**Suggested Labels:**

schedule task, sequence,deployment,Sequence Deployer, TaskDeployer
**Suggested Assignees:**

**Affected Product Version:**
integration studio 7.2.0
  Integration Studio	7.2.0.202012211759	WSO2-Integration-Studio
**OS, DB, other environment details and versions:**    
ubuntu 18.04
**Steps to reproduce:**
new project run it automatically deploying that two temp files
![Screenshot from 2021-04-24 14-47-40](https://user-images.githubusercontent.com/83068814/115953985-124a9380-a50c-11eb-8c35-202de8ba62fd.png)

**Related Issues:**

**Comment by rosensilva** [comment]
Hi @ashoka777,
Can you please share the workspace as a zip file to further investigate?
Also, you can try a new workspace as a workaround for the issue

**Comment by ashoka777** [comment]
Because of OSGi clean error it's came.. I updated the OSGi using
integration studio it's resolved.. thank you..

**Comment by ashoka777** [comment]
> Hi @ashoka777,
> Can you please share the workspace as a zip file to further investigate?
> Also, you can try a new workspace as a workaround for the issue


[workspace doc.zip](https://github.com/wso2/integration-studio/files/6440579/workspace.doc.zip)


here i attached one of my workspace same above problem..
another workspace has larger than 10mb. how can i share in this. it is 27mb zip..
