### ISSUE TITLE
Argument cannot be null: Error in Integrator studio 7.2.0

### ISSUE THREAD

**Issue by karunarathneeshani** [wso2/integration-studio#820]
**Description:**
The following error can be observed in the integrator studio when double click on the call-template mediator from the design view after doing any change from the source view.

**Suggested Labels:**
Integrator studio 7.2.0

![template](https://user-images.githubusercontent.com/28178905/116237934-6ceb2600-a77e-11eb-9161-26c3d133ee9c.png)

**Comment by rosensilva** [comment]
Fixed with https://github.com/wso2/integration-studio/pull/825
