### ISSUE TITLE
No redeploy option for cars in Integration Studio 7.2.0

### ISSUE THREAD

**Issue by isurul28** [wso2/integration-studio#822]
**Description:**
No redeploy option for cars in Integration Studio 7.2.0

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
Integration Studio 7.2.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
Download the Integration studio from wso2 website : https://wso2.com/integration/integration-studio/
Open integration studio and create a simple integration project
Create a new wos2  EI sever 
Run the car on the newly created wso2 EI sever 
Right click on the car file and redeploy option is gone
![redeploy](https://user-images.githubusercontent.com/27796601/116703586-14b75c80-a9e8-11eb-8163-240891d3511c.png)

**Related Issues:**

**Comment by rosensilva** [comment]
Please download the latest integration studio 8.0.0. This issue is fixed in the latest version. https://wso2.com/integration/integration-studio/
