### ISSUE TITLE
local MI does not load the project artifacts

### ISSUE THREAD

**Issue by stefanonegri** [wso2/integration-studio#824]
**Description:**
When I want to run locally a composite project, even if selected, the local micro integrator starts but the project artefacts are not loaded;

**Suggested Labels:**
run local MI

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    
Mac OS

**Steps to reproduce:**

**Related Issues:**

**Comment by rosensilva** [comment]
@sajithaliyanage any idea about this issue?
