### ISSUE TITLE
WS policy template uses org.wso2.carbon.security.util.ServerCrypto as default provider 

### ISSUE THREAD

**Issue by sajithaliyanage** [wso2/integration-studio#840]
**Description:**
$subject

When we are creating a WS security policy file in **Sign and Encrypt-X509 Authentication**  format from the Integration Studio, **org.wso2.carbon.security.util.ServerCrypto** is added as the default provider under rampart encryptionCrypto and signatureCrypto section. However for Micro Integrator runtimes, this provider should be changed as **org.wso2.micro.integrator.security.util.ServerCrypto**

**Suggested Labels:**
type/improvement

**Comment by dulanjalidilmi** [comment]
Since in EI we use **org.wso2.carbon.security.util.ServerCrypto** and in MI we use **org.wso2.micro.integrator.security.util.ServerCrypto**, shall we add a text box to update this through the design view, like we have done for tokenStoreClass.
