### ISSUE TITLE
Dependency issue due to the unavailability of syanpse-core jar in studio-8.0.0

### ISSUE THREAD

**Issue by akAsara** [wso2/integration-studio#849]
**Description:**
There is a dependency issue in the newest studio(8.0.0) due to the unavailability of the relevant synapse-core jar inside the Referenced Libraries folder.

**Suggested Labels:**
integration-studio

**Affected Product Version:**
8.0.0 

**Steps to reproduce:**

1. Download and install the integration studio 8.0.0
2. Create a Mediator project

**Comment by Tharsanan1** [comment]
Followed the reproduce steps and was able to create a project successfully on Windows and Linux. Tested version 8.0.1
