### ISSUE TITLE
artifacts.xml file is not getting updated when Copy-Paste the artifacts in Integration Studio

### ISSUE THREAD

**Issue by karunarathneeshani** [wso2/integration-studio#855]
**Description:**
artifacts.xml file is not getting updated when copy-paste the artifacts in Integration Studio. Therefore, these newly pasted artifacts are getting missed when creating the CAR App.

**Affected Product Version:**
Integration Studio-8.0.0

**Steps to reproduce:**
1. Create a sequence at the Integration Studio project
2. Right-click on the created sequence and click on Copy.
3. Paste the Sequence at the same location.
4. It will ask to rename the sequence.
5. Rename and save.
6. Create the CAR App.
7. The pasted artifact will not be included in the Car app due to artifact details are not getting updated in the artifacts.xml file

**Comment by rosensilva** [comment]
can fix with:https://github.com/wso2/devstudio-tooling-esb/commit/ea8a0b95f93c7fcd6b6412ab5cdf0388a02e7225
