### ISSUE TITLE
Integration Studio Web Views won't work when switch workspace or restart studio

### ISSUE THREAD

**Issue by rosensilva** [wso2/integration-studio#877]
**Description:**
Integration Studio Web Views including Getting Started Page, Connector Page, Help Page, Data Mapper real-time viewer won't work when switching workspace or restart studio.

**Affected Product Version:**
8.0.0

**Steps to reproduce:**
1) Open Integration Studio
2) File->Restart
3) Try opening Help -> Getting Started

**Comment by Tharsanan1** [comment]
Could not reproduce this issue on Linux.
