### ISSUE TITLE
Smooks mediator's resouce key view doesn't show available workspace resources

### ISSUE THREAD

**Issue by wggihan** [wso2/integration-studio#886]
**Description:**
Smooks mediator does not show existing workspace resources when trying to browse through Configuration key entry. 

**Affected Product Version:**
Integration Studio 8.0

**OS, DB, other environment details and versions:**    
macOS Big Sur 11.6

**Comment by imsuneth** [comment]
Can not be reproduced using integration studio 8.1.0-beta
