### ISSUE TITLE
EDI Connector

### ISSUE THREAD

**Issue by HariAnil** [wso2/integration-studio#89]
A built in connector is required in Wso2 to deal with different kinds of EDI operations. The same connector is available in other popular Integration tools and this is a challenge when we want to replace those tools with WSO2 EI.

Some workarounds are possible using Smooks mediator and xml mappings. But it will be convenient and user friendly if we have connectors for this.

**Comment by abeykoon** [comment]
This can be a valid concern for the users who uses EDI heavily. As we have other options for this, given other priorities we will consider this feature has low priority for the next release.
