### ISSUE TITLE
The import org.omg cannot be resolved

### ISSUE THREAD

**Issue by neogreco** [wso2/integration-studio#919]
**Description:**
I'm downloading the git project to run it from source code; because i've problems with the release version.
when i run "mvn clean install" after 20 minutes of downloading and installing packages, ends with this error:

> Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:1.3.0:compile (default-compile) on project org.wso2.integrationstudio.updater: Compilation failure: Compilation failure: 
> [ERROR] /Users/neogreco/git/wso2-integration-studio/integration-studio/components/studio-platform/plugins/org.wso2.integrationstudio.updater/src/org/wso2/integrationstudio/updater/job/UpdateCheckerJob.java:[25] 
> [ERROR] 	import org.omg.PortableInterceptor.SYSTEM_EXCEPTION;
> [ERROR] 	       ^^^^^^^
> [ERROR] The import org.omg cannot be resolved
> [ERROR] 1 problem (1 error)
> [ERROR] -> [Help 1]
> [ERROR] 
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR] 
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
> 

**Affected Product Version:**
Main 

**OS, DB, other environment details and versions:**    
Mac Os Big sur 11.1

**Steps to reproduce:**
Download the git project and  run mvn clean install within the folder.

**Comment by Tharsanan1** [comment]
Could not reproduce it.
