### ISSUE TITLE
Update OAuth Configs in HTTP Endpoints

### ISSUE THREAD

**Issue by SanojPunchihewa** [wso2/integration-studio#937]
**Description:**
Need to update the Studio with  following changes,
- With https://github.com/wso2/wso2-synapse/pull/1796 we have added expression support for OAuth Configs in HTTP Endpoints.
- With https://github.com/wso2/wso2-synapse/pull/1796 we added an option to specify custom params in OAuth request body.
- With https://github.com/wso2/wso2-synapse/pull/1844 Password grant type was introduced to OAuth HTTP endpoints

**Comment by chanikag** [comment]
With https://github.com/wso2/product-ei/issues/5512 we have added a new property called authMode to indicate how the client credentials are passed to the token endpoint. If the authMode is payload it is passed in the request payload. If the authMode is header the client credentials are passed in the authentication header which is the default.
