### ISSUE TITLE
User Setting value get reset when we run the unit test again

### ISSUE THREAD

**Issue by isurul28** [wso2/integration-studio#960]
**Description:**
When we configure settings here(user setting), they are getting reset when we run the tests again.

![image](https://user-images.githubusercontent.com/27796601/143377133-3b69f27e-38ff-4412-8c11-c16f4b7f5663.png)

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
Integration Studio 8.0.0
**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

1. Create a unit test case and run it once
2. Right click on Test case and go to Run as >> Run Configurations...
3. Then you can see under maven build there is a Run unit test config. Go to that and in the user setting you can give your setting.xml file
4. Now run the unit test and it work fine
5. When we run the unit test for the second time this values are getting reset

**Related Issues:**

**Comment by Tharsanan1** [comment]
Could not reproduce the issue. Could you provide the settings.xml file you have used?

**Comment by isurul28** [comment]
Hi 
This has been fixed by a integration studio update released on 13/Dec/21
