### ISSUE TITLE
Cannot generate an API from a Swagger definition

### ISSUE THREAD

**Issue by CarbonHeartDev** [wso2/integration-studio#979]
**Description:**
When I try to create a new Synapse API artifact using the option "Generate API using Swagger definition" I'm able to complete the creation wizard but once I click on finish I don't see any new file nor I get any error, I tried to repeat the procedure with json and yaml Swagger definitions but the issue persists, the version of the definition which I use is OpenAPI 3.0.1

**Suggested Labels:**
8.0.0,bug,swagger

**Suggested Assignees:**

**Affected Product Version:**
Integration Studio 8.0.0

**OS, DB, other environment details and versions:**    
macOS Big Sur 11.6

**Steps to reproduce:**
1. Create a new Integration Project
2. Inside the newly created project start to create a Rest API using the wizard
3. On the first page of the wizard click on "Generate API using Swagger Definition"
4. Import a Swagger definition file (I using the version 3.0.1 of the OpenAPI specification)
5. Click on "Finish"
6. No new file is created and there isn't any error message

**Related Issues:**

**Comment by rosensilva** [comment]
Hi @CarbonHeartDev ,
Can you please share the API file?
