### ISSUE TITLE
Add helm resource support

### ISSUE THREAD

**Issue by prabushi** [wso2/integration-studio#99]
**Description:**
Add Helm resource support for containerised deployment via tooling.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by sajithaliyanage** [comment]
Discontinued the helm based deployments on K8s. Hence, no need to add this feature. However, improved the K8s exporter module with fix: https://github.com/wso2/integration-studio/pull/605
